;;; magpi-launch-tests.el --- Tests for frozen launch specifications -*- lexical-binding: t; -*-

(require 'ert)
(require 'magpi-launch)

(ert-deftest magpi-launch-resolves-thinking-without-transport-artifacts ()
  (let ((spec (magpi-launch-build
               "/tmp/project/" 'low 'reader '(:kind none))))
    (should (equal (magpi-launch-spec-root spec) "/tmp/project/"))
    (should (eq (magpi-launch-spec-thinking spec) 'low))
    (should-not (magpi-launch-spec-requested-model spec))
    (should (eq (magpi-launch-spec-role spec) 'reader))))

(ert-deftest magpi-launch-spec-excludes-transport-artifacts ()
  (let ((slots (mapcar #'car (cl-struct-slot-info 'magpi-launch-spec))))
    (dolist (artifact '(flags first-message name profile effort))
      (should-not (memq artifact slots)))))

(ert-deftest magpi-launch-preserves-semantic-context ()
  (let ((context '(:kind point :file "lib/auth.ex" :line 12 :text "refresh()")))
    (should (eq (magpi-launch-spec-context
                 (magpi-launch-build "/tmp/" nil 'writer context))
                context))))

(ert-deftest magpi-launch-rejects-unknown-semantic-values ()
  (should-error (magpi-launch-build "/tmp/" 'ludicrous 'writer '(:kind none)))
  (should-error (magpi-launch-build "/tmp/" nil 'unknown '(:kind none)))
  (should-error (magpi-launch-build "/tmp/" nil 'writer '(:kind unknown)))
  (should (eq (magpi-launch-role-from-label "r") 'reader))
  (should (eq (magpi-launch-role-from-label "w") 'writer))
  (should-error (magpi-launch-role-from-label "write everything"))
  (should-error (magpi-launch-bind-from-label "nearby"))
  (should-error (magpi-launch-thinking-from-label "ludicrous"))
  (should-error (magpi-launch-build "/tmp/" nil 'writer '(:kind none)
                                    "not-a-canonical-model")))

(ert-deftest magpi-launch-normalizes-blank-authored-input-once ()
  (should-not (magpi-normalize-objective "   "))
  (should-not (magpi-normalize-objective nil))
  (should (equal (magpi-normalize-objective "  Repair token refresh.  ")
                 "Repair token refresh."))
  (should-not (magpi-normalize-model "Inherit"))
  (should-not (magpi-normalize-model "  "))
  (should (equal (magpi-normalize-model "  openai/gpt-4.1  ")
                 "openai/gpt-4.1"))
  (let ((spec (magpi-launch-build "/tmp/" nil 'writer '(:kind none))))
    (should-not (magpi-launch-spec-requested-model spec))))

(ert-deftest magpi-launch-freezes-requested-model-and-thinking ()
  (let ((spec (magpi-launch-build
               "/tmp/" 'high 'writer '(:kind none)
               "anthropic/claude-sonnet")))
    (should (equal (magpi-launch-spec-requested-model spec)
                   "anthropic/claude-sonnet"))
    (should (eq (magpi-launch-spec-thinking spec) 'high)))
  (let ((spec (magpi-launch-build
               "/tmp/" nil 'reader '(:kind none) "Inherit")))
    (should-not (magpi-launch-spec-requested-model spec))
    (should-not (magpi-launch-spec-thinking spec))))

(ert-deftest magpi-launch-model-catalog-is-last-used-then-live-ids ()
  (let ((magpi-launch--catalog (make-hash-table :test #'equal))
        (magpi-launch--last-model (make-hash-table :test #'equal))
        (magpi-launch-models '("Inherit"))
        (root "/tmp/project/"))
    (should (equal (magpi-launch-model-choices root) '("Inherit")))
    (should (equal (magpi-launch-default-model root) "Inherit"))
    (should-not (magpi-launch-remember-model root "Inherit"))
    (should (equal (magpi-launch-remember-model root "openai/gpt-4.1")
                   "openai/gpt-4.1"))
    (should (equal (magpi-launch-store-catalog
                    root '("anthropic/claude-sonnet" "openai/gpt-4.1" ""))
                   '("anthropic/claude-sonnet" "openai/gpt-4.1")))
    (should-not (magpi-launch-store-catalog root nil))
    (should (equal (magpi-launch-default-model root) "openai/gpt-4.1"))
    (should (equal (magpi-launch-model-choices root)
                   '("Inherit" "openai/gpt-4.1" "anthropic/claude-sonnet")))))

(ert-deftest magpi-launch-refresh-catalog-uses-registered-filler ()
  (let ((magpi-launch--catalog (make-hash-table :test #'equal))
        (magpi-launch-catalog-refresh-function
         (lambda (root &optional _handle)
           (magpi-launch-store-catalog root '("openai/gpt-4.1")))))
    (should (equal (magpi-launch-refresh-catalog "/tmp/project/")
                   '("openai/gpt-4.1")))))

(ert-deftest magpi-launch-model-search-is-normalized-and-fuzzy ()
  (should (equal (magpi-launch--fold-model "Grok-4.5") "grok45"))
  (should (magpi-launch--model-query-matches-p "grok4.5" "xai/grok-4.5"))
  (should (magpi-launch--model-query-matches-p "grok45" "xai/grok-4.5"))
  (should (magpi-launch--model-query-matches-p "sol" "openai-codex/gpt-5.6-sol"))
  (should (magpi-launch--model-query-matches-p "g45" "xai/grok-4.5"))
  (should-not (magpi-launch--model-query-matches-p "opus" "xai/grok-4.5"))
  (let ((magpi-launch--catalog (make-hash-table :test #'equal))
        (magpi-launch--last-model (make-hash-table :test #'equal))
        (magpi-launch-models '("Inherit"))
        (root "/tmp/project/"))
    (magpi-launch-store-catalog
     root '("xai/grok-4.5" "openai-codex/gpt-5.6-sol" "openai-codex/gpt-5.6-terra"))
    (should (equal (magpi-launch--filter-models "sol" (magpi-launch-model-choices root))
                   '("openai-codex/gpt-5.6-sol")))
    (should (equal (all-completions "grok4.5" (magpi-launch-model-completion-table root))
                   '("xai/grok-4.5")))))

(ert-deftest magpi-launch-thinking-labels-round-trip ()
  (should (eq (magpi-launch-thinking-from-label "Standard") 'medium))
  (should (eq (magpi-launch-thinking-from-label "Quick") 'low))
  (should (eq (magpi-launch-thinking-from-label "Default") nil))
  (should (equal (magpi-launch-thinking-choice-label 'medium) "Standard"))
  (should (equal (magpi-launch-thinking-label 'high) "high"))
  (should (equal (magpi-launch-thinking-label nil) "default")))

(ert-deftest magpi-launch-default-bind-skips-porcelain ()
  (should (equal (magpi-launch-bind-label 'none) "None"))
  (with-temp-buffer
    (should (eq (magpi-launch-default-bind) 'none)))
  (with-temp-buffer
    (setq buffer-file-name "/tmp/lib/auth.ex")
    (should (eq (magpi-launch-default-bind) 'none))))

(ert-deftest magpi-launch-composes-first-message-from-source-without-prompt ()
  (should-not (magpi-launch-compose-first-message nil '(:kind none)))
  (should-not (magpi-launch-compose-first-message "  " '(:kind none)))
  (should (equal (magpi-launch-compose-first-message "Inspect this" '(:kind none))
                 "Inspect this"))
  (let* ((context '(:kind point :file "lib/auth.ex" :line 12 :text "refresh()"))
         (source-only (magpi-launch-compose-first-message nil context))
         (combined (magpi-launch-compose-first-message "Inspect this" context)))
    (should (string-match-p "lib/auth.ex:12" source-only))
    (should (string-match-p "refresh()" source-only))
    (should-not (string-match-p "Inspect this" source-only))
    (should (string-prefix-p "Inspect this" combined))
    (should (string-match-p "refresh()" combined))))

(provide 'magpi-launch-tests)
;;; magpi-launch-tests.el ends here
