;;; magpi-life-play.el --- e2e plays (specs/proposal/e2e-play.org) -*- lexical-binding: t; -*-

;; One-shot spike: second Emacs, toy repo, exogenous gauges.
;; Not a test framework.  Unit-marked rows stay in ERT.

(require 'cl-lib)
(require 'seq)
(require 'subr-x)
(require 'magpi-seams)
(require 'magpi-test-repo)

(let ((root (or (magpi-seams-straight-root)
                (error "life plays need a straight build (set MAGPI_STRAIGHT_BUILD)"))))
  (dolist (pkg '(compat cond-let llama seq transient with-editor magit-section magit
                 timeout spinner pcre2el pimacs))
    (add-to-list 'load-path (expand-file-name (symbol-name pkg) root))))

;; Full Magit hangs in some batch sandboxes; mode/section are the glance seam.
(require 'magit-section)
(require 'magit-mode)
(require 'pimacs)
(require 'magpi)

(defvar magpi-play--results nil)
(defvar magpi-play--skip-pi nil)

(cl-defstruct magpi-play-backend file-at-spawn)

(cl-defmethod magpi-backend-spawn ((backend magpi-play-backend) action _listener)
  (let ((root (or (magpi-action-source-root action)
                  (and (magpi-action-launch action)
                       (magpi-launch-spec-root (magpi-action-launch action))))))
    (setf (magpi-play-backend-file-at-spawn backend)
          (and root (file-exists-p (magpi-store-file root 'actions
                                                    (magpi-action-id action))))))
  'play-handle)

(cl-defmethod magpi-backend-send-initial ((_backend magpi-play-backend) _handle _action)
  nil)

(cl-defmethod magpi-backend-visit ((_backend magpi-play-backend) _handle)
  nil)

(cl-defmethod magpi-backend-live-p ((_backend magpi-play-backend) handle)
  (and handle (not (eq handle 'dead))))

(cl-defmethod magpi-backend-session-ref ((_backend magpi-play-backend) _handle)
  nil)

(defun magpi-play--reset ()
  (when (timerp magpi--refresh-timer)
    (cancel-timer magpi--refresh-timer))
  (setq magpi--actions (make-hash-table :test #'equal)
        magpi--handles (make-hash-table :test #'equal)
        magpi--intentions (make-hash-table :test #'equal)
        magpi--refresh-timer nil
        magpi-launch--catalog (make-hash-table :test #'equal)
        magpi-launch--last-model (make-hash-table :test #'equal)))

(defun magpi-play--record (id status &optional detail)
  (push (list id status detail) magpi-play--results)
  (message "play %s %s%s" id status
           (if detail (format " — %s" detail) "")))

(defmacro magpi-play (id &rest body)
  (declare (indent 1))
  `(condition-case err
       (progn ,@body
              (magpi-play--record ,id 'pass))
     (error
      (magpi-play--record ,id 'fail (error-message-string err)))))

(defun magpi-play--plist-has (data key)
  (let (found)
    (while data
      (when (eq (pop data) key)
        (setq found t))
      (pop data))
    found))

(defun magpi-play--session-id-flags (flags)
  (let (ids)
    (while flags
      (if (equal (car flags) "--session-id")
          (progn (push (cadr flags) ids)
                 (setq flags (cddr flags)))
        (setq flags (cdr flags))))
    (nreverse ids)))

(defun magpi-play--jsonl (sess)
  (when (file-directory-p sess)
    (directory-files sess t "\\.jsonl\\'" t)))

(defun magpi-play--file-under-p (file dir)
  "Return non-nil when FILE is a path string under DIR. FILE need not exist."
  (let ((file (and (stringp file) (expand-file-name file)))
        (dir (file-name-as-directory (expand-file-name dir))))
    (and file (string-prefix-p dir file))))

(defun magpi-play--stderr ()
  (if (get-buffer "*pimacs-stderr*")
      (with-current-buffer "*pimacs-stderr*" (buffer-string))
    ""))

(defun magpi-play--kill-agents ()
  (when (boundp 'pimacs--agents)
    (maphash
     (lambda (_key proc)
       (when (and (processp proc) (process-live-p proc))
         (ignore-errors (delete-process proc))))
     pimacs--agents)
    (accept-process-output nil 0.15)
    (clrhash pimacs--agents))
  (when-let ((buf (get-buffer "*pimacs-stderr*")))
    (when-let ((proc (get-buffer-process buf)))
      (ignore-errors (delete-process proc)))))

(defun magpi-play--wait (pred seconds)
  (let ((deadline (+ (float-time) seconds)))
    (while (and (not (funcall pred)) (< (float-time) deadline))
      (accept-process-output nil 0.1))
    (funcall pred)))

(defun magpi-play--get-state (handle)
  (let ((chat (magpi-pimacs-handle-chat-buffer handle))
        data last-err tries)
    (unless (buffer-live-p chat)
      (error "no chat buffer for get_state"))
    (with-current-buffer chat
      (while (and (not data) (< (or tries 0) 4))
        (setq tries (1+ (or tries 0)))
        (condition-case err
            (let ((resp (pimacs--send-command-sync "get_state" '())))
              (if (pimacs--response-success-p resp)
                  (setq data (plist-get resp :data))
                (setq last-err (format "unsuccessful: %S" resp))))
          (error (setq last-err err)))
        (unless data (accept-process-output nil 0.2))))
    (or data (error "get_state failed: %S\nstderr: %s" last-err
                    (magpi-play--stderr)))))

(defun magpi-play--spawn-action (root id &optional intention-id role)
  "Spawn Action ID in ROOT through Magpi, capturing Pimacs flags."
  (let ((default-directory root)
        captured
        (role (or role 'writer)))
    (cl-letf (((symbol-function 'magpi-store-new-id) (lambda () id))
              ((symbol-function 'pimacs-chat)
               (let ((orig (symbol-function 'pimacs-chat)))
                 (lambda (&rest args)
                   (setq captured (copy-sequence pimacs-flags))
                   (apply orig args)))))
      (magpi-spawn-from-options
       (append (list :role role :context-kind 'none :thinking 'medium)
               (when intention-id (list :intention-id intention-id)))))
    (let ((handle (gethash id magpi--handles)))
      (unless handle (error "spawn produced no handle"))
      (list :handle handle :flags captured
            :action (gethash id magpi--actions)))))

(defun magpi-play-B3-failed-remove ()
  (magpi-test-with-repo (root "magpi-life-B3-")
    (let ((intention (magpi-intention-create-record "Discard fail" root "drop"))
          path orig)
      (setq intention (magpi-intention-ensure-worktree intention)
            path (magpi-intention-worktree-path intention))
      (with-temp-file (expand-file-name "dirty" path)
        (insert "uncommitted\n"))
      (setq orig (symbol-function 'magpi-git))
      (condition-case nil
          (cl-letf (((symbol-function 'magpi-git)
                     (lambda (dir &rest args)
                       (if (equal (car args) "worktree")
                           (user-error "forced remove fail")
                         (apply orig dir args)))))
            (magpi-intention-discard-record intention)
            (error "discard should have failed after persist"))
        (error nil))
      (setq intention (magpi-intention-load root "drop"))
      (unless (eq (magpi-intention-state intention) 'discarded)
        (error "state is %S, expected discarded" (magpi-intention-state intention)))
      (when (not (file-directory-p path))
        (error "worktree vanished despite forced remove fail")))))

(defun magpi-play-C1-persist-before-spawn ()
  (magpi-test-with-repo (root "magpi-life-C1-")
    (magpi-play--reset)
    (let ((default-directory root)
          (magpi-backend (make-magpi-play-backend)))
      (cl-letf (((symbol-function 'magpi-store-new-id) (lambda () "c1aaaaaaaaaa")))
        (magpi-spawn-from-options '(:role writer :context-kind none)))
      (unless (magpi-play-backend-file-at-spawn magpi-backend)
        (error "action file missing when adapter returned"))
      (let ((data (magpi-store-read (magpi-store-file root 'actions "c1aaaaaaaaaa"))))
        (unless (equal (plist-get data :chat-ref) "c1aaaaaaaaaa")
          (error "chat-ref %S" (plist-get data :chat-ref)))
        (when (magpi-play--plist-has data :observation)
          (error "observation on disk"))
        (when (magpi-play--plist-has data :launch)
          (error "launch on disk"))))))

(defun magpi-play-C2-hydrate-without-theatre ()
  (magpi-test-with-repo (root "magpi-life-C2-")
    (magpi-play--reset)
    (let ((default-directory root)
          (magpi-backend (make-magpi-play-backend))
          action)
      (cl-letf (((symbol-function 'magpi-store-new-id) (lambda () "c2aaaaaaaaaa")))
        (magpi-spawn-from-options '(:role writer :context-kind none)))
      (clrhash magpi--actions)
      (clrhash magpi--handles)
      (setq action (seq-find (lambda (a)
                               (and (magpi-action-p a)
                                    (equal (magpi-action-id a) "c2aaaaaaaaaa")))
                             (magpi--actions-for-root root)))
      (unless (magpi-action-p action)
        (error "glance missed action"))
      (when (gethash "c2aaaaaaaaaa" magpi--actions)
        (error "paint wrote the registry"))
      (when (magpi-action-observation action)
        (error "glance painted observation"))
      (unless (equal (magpi-action-chat-ref action) "c2aaaaaaaaaa")
        (error "chat-ref became %S" (magpi-action-chat-ref action)))
      (let ((suffix (magpi-status--heading-suffix action))
            (glance (magpi-status--glance (magpi-action-observation action))))
        (unless (string-match-p "\\bcold\\b" suffix)
          (error "glance suffix %S is not cold" suffix))
        (when (string-match-p "starting" suffix)
          (error "glance painted starting"))
        (when glance
          (error "pending glance %S" glance))))))

(defun magpi-play-C3-standalone-watermark ()
  (magpi-test-with-repo (root "magpi-life-C3-")
    (magpi-play--reset)
    (let ((default-directory root)
          (magpi-backend (make-magpi-play-backend))
          (head (string-trim (magpi-test-repo-git root "rev-parse" "HEAD")))
          action opened ranged)
      (cl-letf (((symbol-function 'magpi-store-new-id) (lambda () "c3aaaaaaaaaa")))
        (setq action (magpi-spawn-from-options '(:role writer :context-kind none))))
      (unless (equal (magpi-action-spawn-oid action) head)
        (error "spawn-oid %S != HEAD %s" (magpi-action-spawn-oid action) head))
      (when (magpi-action-intention-id action)
        (error "standalone grew an intention"))
      (cl-letf (((symbol-function 'magit-status)
                 (lambda (dir) (setq opened dir)))
                ((symbol-function 'magit-diff-range)
                 (lambda (range _) (setq ranged range))))
        (magpi--standalone-changes 'status '(:action-id "c3aaaaaaaaaa"))
        (magpi--standalone-changes 'diff '(:action-id "c3aaaaaaaaaa")))
      (unless (file-equal-p opened root)
        (error "m did not open source-root"))
      (unless (equal ranged (format "%s..HEAD" head))
        (error "d range %S" ranged))
      (condition-case nil
          (progn (magpi--standalone-changes 'commit '(:action-id "c3aaaaaaaaaa"))
                 (error "commit should refuse"))
        (error nil)))))

(defun magpi-play-C4-dual-membership ()
  (magpi-test-with-repo (root "magpi-life-C4-")
    (magpi-play--reset)
    (let ((default-directory root)
          (magpi-backend (make-magpi-play-backend))
          intention action lease text)
      (setq intention (magpi-intention-create-record "Shared why" root "intc4"))
      (puthash "intc4" intention magpi--intentions)
      (cl-letf (((symbol-function 'magpi-store-new-id) (lambda () "c4aaaaaaaaaa"))
                ((symbol-function 'magpi--intention) (lambda (_id) intention)))
        (setq action (magpi-spawn-from-options
                      '(:intention-id "intc4" :role writer :context-kind none))))
      (setq intention (gethash "intc4" magpi--intentions)
            lease (magpi-intention-writer-lease intention))
      (unless (equal (plist-get lease :action-id) "c4aaaaaaaaaa")
        (error "writer lease lost"))
      (let ((data (magpi-store-read (magpi-intention--file root "intc4"))))
        (when (magpi-play--plist-has data :action-ids)
          (error "action-ids on disk")))
      (unless (equal (mapcar #'magpi-action-id
                             (magpi--actions-for-intention "intc4"))
                     '("c4aaaaaaaaaa"))
        (error "index missed action"))
      (unless (equal (magpi-action-intention-id action) "intc4")
        (error "Action.intention-id missing"))
      (setq text
            (with-temp-buffer
              (magit-insert-section (magpi-status root)
                (magpi-status--insert-records (list intention) (list action)))
              (buffer-string)))
      (unless (string-match-p "Shared why" text)
        (error "intention glance missing"))
      (unless (string-match-p "starting\\|cold\\|New task" text)
        (error "nested action glance missing: %s" text))
      (unless (equal (plist-get (magpi-intention-writer-lease intention) :action-id)
                     "c4aaaaaaaaaa")
        (error "lease dropped when action-ids excised")))))

(defun magpi-play--pi-ready-p ()
  (and (not magpi-play--skip-pi)
       (executable-find "pi")
       (featurep 'pimacs)))

(defun magpi-play--with-pi (root sess fn)
  (make-directory sess t)
  (let ((process-environment
         (cons "PI_OFFLINE=1"
               (magpi-pimacs--without-parent-session process-environment)))
        (pimacs-flags (list "--session-dir" sess "--no-extensions" "--offline"))
        (pimacs-sync-request-timeout 3)
        (default-directory root)
        (magpi-backend (make-magpi-pimacs-backend)))
    (setenv "PI_OFFLINE" "1")
    (magpi-play--reset)
    (unwind-protect
        (funcall fn)
      (magpi-play--kill-agents))))

(cl-defun magpi-play-D-chain ()
  "D1 birth, D2 kill, D3 RET, D4 killed buffer."
  (unless (magpi-play--pi-ready-p)
    (magpi-play--record 'D "skip" "no pi/pimacs")
    (cl-return-from magpi-play-D-chain nil))
  (let* ((root (magpi-test-repo-create "magpi-life-pi-"))
         (sess (expand-file-name "sessions" root))
         (id "magpi-life-aaaaaaaa")
         ok)
    (unwind-protect
        (magpi-play--with-pi
         root sess
         (lambda ()
           (let* ((born (magpi-play--spawn-action root id))
                  (handle (plist-get born :handle))
                  (flags (plist-get born :flags))
                  (ids (magpi-play--session-id-flags flags))
                  state)
             (unless (equal ids (list id))
               (error "D1 flags --session-id %S" ids))
             (unless (magpi-play--wait
                      (lambda () (magpi-backend-live-p magpi-backend handle))
                      8)
               (error "D1 agent never live"))
             (setq state (magpi-play--get-state handle))
             (unless (equal (plist-get state :sessionId) id)
               (error "D1 sessionId %S" (plist-get state :sessionId)))
             (unless (magpi-play--file-under-p (plist-get state :sessionFile) sess)
               (error "D1 sessionFile %S not under %s"
                      (plist-get state :sessionFile) sess))
             (magpi-play--record 'D1 'pass)
             ;; D2
             (let ((agent (gethash (magpi-pimacs-handle-key handle) pimacs--agents))
                   (chat (magpi-pimacs-handle-chat-buffer handle)))
               (unless (processp agent)
                 (error "D2 no agent process"))
               (delete-process agent)
               (magpi-play--wait
                (lambda ()
                  (not (let ((cur (gethash (magpi-pimacs-handle-key handle)
                                           pimacs--agents)))
                         (and (processp cur) (process-live-p cur)))))
                4)
               (when (magpi-backend-live-p magpi-backend handle)
                 (error "D2 live-p true on dead process"))
               (when (and (buffer-live-p chat)
                          (not (magpi-backend-live-p magpi-backend handle)))
                 (message "D2 split: buffer live, live-p false"))
               (magpi-play--record 'D2 'pass))
             ;; D3
             (magpi--visit-or-open-action id)
             (setq handle (gethash id magpi--handles))
             (unless (magpi-play--wait
                      (lambda () (magpi-backend-live-p magpi-backend handle))
                      8)
               (error "D3 not live after RET"))
             (when (magpi-pimacs-handle-initial-sent handle)
               (error "D3 send-initial fired"))
             (setq state (magpi-play--get-state handle))
             (unless (equal (plist-get state :sessionId) id)
               (error "D3 sessionId %S" (plist-get state :sessionId)))
             (magpi-play--record 'D3 'pass)
             ;; D4 — Pimacs kills the agent on chat kill-buffer-hook.
             (magpi-play 'D4
               (let ((old (magpi-pimacs-handle-chat-buffer handle)))
                 (kill-buffer old)
                 (unless (magpi-backend-live-p magpi-backend handle)
                   (error "D4 process died with buffer"))
                 (magpi-backend-visit magpi-backend handle)
                 (unless (buffer-live-p (magpi-pimacs-handle-chat-buffer handle))
                   (error "D4 visit did not rebuild chat"))
                 (unless (magpi-backend-live-p magpi-backend handle)
                   (error "D4 live-p false after visit"))
                 (setq state (magpi-play--get-state handle))
                 (unless (equal (plist-get state :sessionId) id)
                   (error "D4 sessionId %S" (plist-get state :sessionId))))))
           (setq ok t)))
      (unless ok
        (message "Magpi play evidence retained: %s" root)
        (message "sessions: %s" (magpi-play--jsonl sess))
        (message "stderr: %s" (magpi-play--stderr)))
      (when ok
        (magpi-play--kill-agents)
        (when (file-directory-p root)
          (delete-directory root t))))))

(cl-defun magpi-play-D5-two-actions ()
  (unless (magpi-play--pi-ready-p)
    (magpi-play--record 'D5 'skip "no pi/pimacs")
    (cl-return-from magpi-play-D5-two-actions nil))
  (let* ((root (magpi-test-repo-create "magpi-life-D5-"))
         (sess (expand-file-name "sessions" root))
         ok)
    (unwind-protect
        (magpi-play--with-pi
         root sess
         (lambda ()
           (let ((intention (magpi-intention-create-record "Two actions" root "intd5"))
                 one two s1 s2)
             (puthash "intd5" intention magpi--intentions)
             (cl-letf (((symbol-function 'magpi--intention)
                        (lambda (_id) (gethash "intd5" magpi--intentions))))
               (setq one (magpi-play--spawn-action root "magpi-life-bbbbbbbb" "intd5" 'writer)
                     two (magpi-play--spawn-action root "magpi-life-cccccccc" "intd5" 'reader)))
             (unless (magpi-play--wait
                      (lambda ()
                        (and (magpi-backend-live-p magpi-backend (plist-get one :handle))
                             (magpi-backend-live-p magpi-backend (plist-get two :handle))))
                      8)
               (error "D5 agents not both live"))
             (let ((n1 (magpi-pimacs--session-name (plist-get one :action)))
                   (n2 (magpi-pimacs--session-name (plist-get two :action))))
               (unless (and (string-suffix-p "magpi-life-bbbbbbbb" n1)
                            (string-suffix-p "magpi-life-cccccccc" n2)
                            (not (equal n1 n2)))
                 (error "D5 names %S %S" n1 n2)))
             (unless (equal (magpi-play--session-id-flags (plist-get one :flags))
                            '("magpi-life-bbbbbbbb"))
               (error "D5 first flags %S" (plist-get one :flags)))
             (unless (equal (magpi-play--session-id-flags (plist-get two :flags))
                            '("magpi-life-cccccccc"))
               (error "D5 second flags %S" (plist-get two :flags)))
             (let ((st1 (magpi-play--get-state (plist-get one :handle)))
                   (st2 (magpi-play--get-state (plist-get two :handle))))
               (setq s1 (plist-get st1 :sessionId)
                     s2 (plist-get st2 :sessionId))
               (unless (and (equal s1 "magpi-life-bbbbbbbb")
                            (equal s2 "magpi-life-cccccccc")
                            (not (equal s1 s2)))
                 (error "D5 sessionIds %S %S" s1 s2))
               (unless (and (magpi-play--file-under-p (plist-get st1 :sessionFile) sess)
                            (magpi-play--file-under-p (plist-get st2 :sessionFile) sess)
                            (not (equal (plist-get st1 :sessionFile)
                                        (plist-get st2 :sessionFile))))
                 (error "D5 sessionFile %S %S"
                        (plist-get st1 :sessionFile)
                        (plist-get st2 :sessionFile)))))
           (setq ok t)))
      (unless ok
        (message "Magpi play evidence retained: %s" root)
        (message "sessions: %s" (magpi-play--jsonl sess)))
      (when ok
        (magpi-play--kill-agents)
        (when (file-directory-p root)
          (delete-directory root t))))))

(cl-defun magpi-play-D6-hydrate-ret ()
  (unless (magpi-play--pi-ready-p)
    (magpi-play--record 'D6 'skip "no pi/pimacs")
    (cl-return-from magpi-play-D6-hydrate-ret nil))
  (let* ((root (magpi-test-repo-create "magpi-life-D6-"))
         (sess (expand-file-name "sessions" root))
         (id "magpi-life-dddddddd")
         ok)
    (unwind-protect
        (magpi-play--with-pi
         root sess
         (lambda ()
           (let* ((born (magpi-play--spawn-action root id))
                  (handle (plist-get born :handle))
                  loaded state)
             (unless (magpi-play--wait
                      (lambda () (magpi-backend-live-p magpi-backend handle))
                      8)
               (error "D6 birth not live"))
             (magpi-play--kill-agents)
             (clrhash magpi--actions)
             (clrhash magpi--handles)
             (setq loaded (seq-find (lambda (a)
                                      (and (magpi-action-p a)
                                           (equal (magpi-action-id a) id)))
                                    (magpi--actions-for-root root)))
             (unless (equal (magpi-action-chat-ref loaded) id)
               (error "D6 chat-ref %S" (magpi-action-chat-ref loaded)))
             (when (gethash id magpi--actions)
               (error "D6 paint wrote the registry"))
             (when (magpi-action-observation loaded)
               (error "D6 glance painted observation"))
             (when (string-match-p "starting"
                                   (magpi-status--heading-suffix loaded))
               (error "D6 glance painted starting"))
             (magpi--visit-or-open-action id)
             (setq handle (gethash id magpi--handles))
             (unless (magpi-play--wait
                      (lambda () (magpi-backend-live-p magpi-backend handle))
                      8)
               (error "D6 RET not live"))
             (setq state (magpi-play--get-state handle))
             (unless (equal (plist-get state :sessionId) id)
               (error "D6 minted %S" (plist-get state :sessionId))))
           (setq ok t)))
      (unless ok
        (message "Magpi play evidence retained: %s" root)
        (message "sessions: %s" (magpi-play--jsonl sess)))
      (when ok
        (magpi-play--kill-agents)
        (when (file-directory-p root)
          (delete-directory root t))))))

(defun magpi-life-play-run (&optional which)
  "Run life plays.  WHICH is git, pi, or all (default)."
  (setq magpi-play--results nil
        magpi-play--skip-pi (eq which 'git)
        which (or which 'all))
  (magpi-play--reset)
  (when (memq which '(git all))
    (magpi-play 'B3-failed-remove (magpi-play-B3-failed-remove))
    (magpi-play 'C1 (magpi-play-C1-persist-before-spawn))
    (magpi-play 'C2 (magpi-play-C2-hydrate-without-theatre))
    (magpi-play 'C3 (magpi-play-C3-standalone-watermark))
    (magpi-play 'C4 (magpi-play-C4-dual-membership)))
  (when (memq which '(pi all))
    (if (not (and (executable-find "pi") (featurep 'pimacs)))
        (message "life-pi skipped: pi or pimacs missing")
      (condition-case err
          (magpi-play-D-chain)
        (error (magpi-play--record 'D1-D3 'fail (error-message-string err))))
      (magpi-play 'D5 (magpi-play-D5-two-actions))
      (magpi-play 'D6 (magpi-play-D6-hydrate-ret))))
  (let* ((fails (seq-filter (lambda (row) (eq (nth 1 row) 'fail))
                            magpi-play--results))
         (passes (seq-filter (lambda (row) (eq (nth 1 row) 'pass))
                             magpi-play--results)))
    (message "plays pass=%d fail=%d skip/other=%d"
             (length passes) (length fails)
             (- (length magpi-play--results) (length passes) (length fails)))
    (magpi-play--kill-agents)
    (magpi-play--reset)
    (when noninteractive
      (kill-emacs (if fails 1 0)))
    (when fails
      (error "life plays failed: %S" fails))
    magpi-play--results))

(provide 'magpi-life-play)
;;; magpi-life-play.el ends here
